### ISSUE TITLE
Discussion: "Organization: Select one [carat]" in sidebar

### ISSUE THREAD

**Issue by jcscottiii** [18F/cf-deck#56]
Thoughts on having it as just "Organizations [carat]"?
![image](https://cloud.githubusercontent.com/assets/7788930/9182330/105aa358-3f78-11e5-9bd8-bcfacde9259c.png)
Should we shorten this text? If a user 1) makes the width of their window small or 2) opens their developer console even while their width is fairly large, it will cause the text to go to the next line.

@ramirezg

**Comment by ramirezg** [comment]
I just shortened it for now in #61
